import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const Ownerstyles = StyleSheet.create({
  mainContainer: {
    backgroundColor: '#ECF2FF',
    height: '100%',
    width: 400,
  },
  Titletext: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3E54AC',
    marginTop: 40,
    marginLeft: 40,
  },
  Imageitem: {
    height: 190,
    width: 190,
    // justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 100,
    marginRight: 90,
    marginTop: 20,
  },
  scrollView: {
    height: 100,
    width: 200,
    justifyContent: 'center',
    marginTop: 10,
  },
  Itemname: {
    color: '#3E54AC',
    fontSize: 18,
    fontFamily: 'poppins',
    // marginLeft: 35,
    fontWeight: '700',
    marginTop: 15,
  },
  Namefield: {
    height: 48,
    width: 250,
    backgroundColor: '#FFFFFF',
    marginTop: 15,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#3E54AC',
    shadowOpacity: 3,
  },
  scroll: {
    marginLeft: 54,
    width: 280,
    height: '100%',
    // alignItems : 'center',
  },
  Descriptionfield: {
    height: 110,
    width: 250,
    backgroundColor: '#FFFFFF',
    marginTop: 15,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#3E54AC',
    shadowOpacity: 3,
    shadowRadius: 3,
  },
  Scrollcontainer: {
    // height: 500,
    // width: 900,
    marginLeft: 20,
  },
  genderText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#3E54AC',
    marginTop: 10,
    alignItems: 'center',
  },
  dropdowntext: {
    justifyContent: 'center',
    color: Colors.iconscolor,
    fontSize: 18,
    fontFamily: 'poppins',
    fontWeight: '700',
    marginTop: 15,
    alignItems: 'center',
  },
  dropdownContainer: {
    height: 48,
    width: 250,
    backgroundColor: '#FFFFFF',
    marginTop: 15,
    borderRadius: 10,
    // elevation: 3,
    // justifyContent: 'center',
    alignItems: 'center',
  },
  dropdown: {
    backgroundColor: '#FFFFFF',
    marginTop: 15,
    borderRadius: 5,
    height: 48,
    width: 250,
    alignItems: 'center',
  },
  dropConatiner: {
    height: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
  DropdownContainer: {
    height: 48,
    width: 250,
    backgroundColor: 'white',
    alignItems: 'center',
    marginTop: 10,
    // marginLeft: 40,
  },
});
export default Ownerstyles;
